/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pepega;

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.paint.Color;
import javafx.scene.*;
import gui.GameView;
import gui.Controller;
public class App extends Application {
    @Override
    public void start(Stage stage){
        Group root = new Group();
        Scene scene = new Scene(root, 800, 800, Color.rgb(0,0,0));
        GameView gv = new GameView(1);
        
        Controller controller = new Controller(scene);
        controller.setKuffo(gv.getKuffo());
        controller.activate();

        root.getChildren().add(gv.getCanvas());
        stage.setScene(scene);
        stage.setTitle("Pepegahyppely");
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
